apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp2-docker-springboot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp2-docker-springboot
  template:
    metadata:
      labels:
        app: tp2-docker-springboot
    spec:
      containers:
        - name: tp2-docker-springboot
          image: tp2-docker-springboot:latest
          ports:
            - containerPort: 8080
