apiVersion: v1
kind: Service
metadata:
  name: tp2-docker-springboot-service
spec:
  type: LoadBalancer
  selector:
    app: tp2-docker-springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
